2021-04-14 10:52:55,234 INFO    MainThread:23260 [wandb_setup.py:_flush():69] setting env: {}
2021-04-14 10:52:55,234 INFO    MainThread:23260 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-14 10:52:55,235 INFO    MainThread:23260 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-14 10:52:55,236 INFO    MainThread:23260 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\rapha\Documents\GitHub\fairlearn-pytorch\wandb\run-20210414_105255-tiqpkj5q\logs\debug.log
2021-04-14 10:52:55,236 INFO    MainThread:23260 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\rapha\Documents\GitHub\fairlearn-pytorch\wandb\run-20210414_105255-tiqpkj5q\logs\debug-internal.log
2021-04-14 10:52:55,237 INFO    MainThread:23260 [wandb_init.py:init():367] calling init triggers
2021-04-14 10:52:55,238 INFO    MainThread:23260 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'run_name': 'first-trial-sex-noDP', 'architecture': 'MLP', 'dataset': 'adult', 'batch_size': 32, 'n_epoch': 20, 'learning_rate': 0.001}
2021-04-14 10:52:55,238 INFO    MainThread:23260 [wandb_init.py:init():416] starting backend
2021-04-14 10:52:55,238 INFO    MainThread:23260 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-04-14 10:52:55,249 INFO    MainThread:23260 [backend.py:ensure_launched():123] starting backend process...
2021-04-14 10:52:55,499 INFO    MainThread:23260 [backend.py:ensure_launched():128] started backend process with pid: 24552
2021-04-14 10:52:55,504 INFO    MainThread:23260 [wandb_init.py:init():421] backend started and connected
2021-04-14 10:52:55,507 INFO    MainThread:23260 [wandb_init.py:init():461] updated telemetry
2021-04-14 10:52:55,511 INFO    MainThread:23260 [wandb_init.py:init():480] communicating current version
2021-04-14 10:52:57,962 INFO    MainThread:23260 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.26 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-14 10:52:57,963 INFO    MainThread:23260 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-04-14 10:52:58,393 INFO    MainThread:23260 [wandb_init.py:init():518] starting run threads in backend
2021-04-14 10:53:03,477 INFO    MainThread:23260 [wandb_run.py:_console_start():1480] atexit reg
2021-04-14 10:53:03,478 INFO    MainThread:23260 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.WRAP
2021-04-14 10:53:03,479 INFO    MainThread:23260 [wandb_run.py:_redirect():1378] Wrapping output streams.
2021-04-14 10:53:03,479 INFO    MainThread:23260 [wandb_run.py:_redirect():1394] Redirects installed.
2021-04-14 10:53:03,479 INFO    MainThread:23260 [wandb_init.py:init():542] run started, returning control to user process
2021-04-14 10:53:28,487 INFO    MainThread:23260 [wandb_run.py:_atexit_cleanup():1450] got exitcode: 1
2021-04-14 10:53:28,488 INFO    MainThread:23260 [wandb_run.py:_restore():1422] restore
2021-04-14 10:53:31,387 ERROR   MainThread:23260 [wandb_run.py:_atexit_cleanup():1468] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1458, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 1594, in _on_finish
    self.history._flush()
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\wandb_run.py", line 790, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\sdk\interface\interface.py", line 221, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\util.py", line 655, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\wandb\util.py", line 622, in default
    return json.JSONEncoder.default(self, obj)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ErrorRate is not JSON serializable
